@php($plan = Guidelines::plan())
> This file is auto-generated by Laravel Boost. Do not edit it directly — changes will be overwritten. Edit the source files in your AI guidelines folder or installed packages instead.

@foreach ($plan->always as $package => $files)
# {{ $package }} Guidelines

@foreach ($files as $file)
{!! trim(file_get_contents($file->path)) !!}

@endforeach
@endforeach
@if ($plan->hasIndex())
# Guidelines from installed packages

Read these when you are about to touch a matching path — before creating or editing the file, not after.
@if ($plan->rows !== [])

| Globs | File |
|---|---|
@foreach ($plan->rows as $row)
| {!! $row->globsAsMarkdown() !!} | {{ $row->relativePath }} |
@endforeach
@endif
@if ($plan->pointers !== [])

These packages ship their own index — read it first, then the file it points to:

@foreach ($plan->pointers as $package => $path)
- {{ $package }}: {{ $path }}
@endforeach
@endif
@endif
@if ($plan->inlined !== [])
@if ($plan->isIndexMode() && $plan->hasIndex())

These files ship no glob metadata, so they are included in full:
@endif

@foreach ($plan->inlined as $package => $files)
# {{ $package }} Guidelines{{ $plan->hasAlways($package) ? ' (continued)' : '' }}

@foreach ($files as $file)
{!! trim(file_get_contents($file->path)) !!}

@endforeach
@endforeach
@endif
