> This file is auto-generated by Laravel Boost. Do not edit it directly — changes will be overwritten. Edit the source files in your AI guidelines folder or installed packages instead.

@foreach (Guidelines::discover() as $package => $files)
# {{ $package }} Guidelines

@foreach ($files as $file)
{!! trim(file_get_contents($file)) !!}

@endforeach

@endforeach
